_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
app:
    value: vjepa
data:
    value:
        batch_size: 16
        clip_duration: null
        crop_size: 224
        dataset_type: VideoDataset
        datasets:
            - ~/saycam_files.csv
        decode_one_clip: true
        filter_short_videos: false
        num_clips: 1
        num_frames: 16
        num_workers: 3
        patch_size: 16
        pin_mem: true
        sampling_rate: 4
        tubelet_size: 2
data_aug:
    value:
        auto_augment: false
        motion_shift: false
        random_resize_aspect_ratio:
            - 0.75
            - 1.35
        random_resize_scale:
            - 0.3
            - 1
        reprob: 0
logging:
    value:
        folder: /scratch/eys8549/vjepa_training
        write_tag: jepa
loss:
    value:
        loss_exp: 1
        reg_coeff: 0
mask:
    value:
        - aspect_ratio:
            - 0.75
            - 1.5
          max_keep: null
          max_temporal_keep: 1
          num_blocks: 8
          spatial_scale:
            - 0.15
            - 0.15
          temporal_scale:
            - 1
            - 1
        - aspect_ratio:
            - 0.75
            - 1.5
          max_keep: null
          max_temporal_keep: 1
          num_blocks: 2
          spatial_scale:
            - 0.7
            - 0.7
          temporal_scale:
            - 1
            - 1
meta:
    value:
        dtype: bfloat16
        eval_freq: 100
        load_checkpoint: false
        read_checkpoint: null
        seed: 234
        use_sdpa: true
model:
    value:
        model_name: vit_large
        pred_depth: 12
        pred_embed_dim: 384
        uniform_power: true
        use_mask_tokens: true
        zero_init_mask_tokens: true
nodes:
    value: 16
optimization:
    value:
        clip_grad: 10
        ema:
            - 0.998
            - 1
        epochs: 200
        final_lr: 1e-06
        final_weight_decay: 0.4
        ipe: 300
        ipe_scale: 1.25
        lr: 0.000625
        start_lr: 0.0002
        warmup: 40
        weight_decay: 0.04
tasks_per_node:
    value: 8
